version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    # For each dependencies group, dependabot will open a PR containing
    # the new versions available for that group.
    groups:
      # wgpu dependencies group
      wgpu-dependencies:
        patterns:
        - "futures-intrusive"
        - "pollster"
        - "text_placeholder"
        - "wgpu"
      # wasm dependencies group
      wasm-bindgen-dependencies:
        patterns:
        - "js-sys"
        - "wasm-bindgen"
        - "wasm-bindgen-futures"
        - "wasm-logger"
        - "wasm-timer"
