[workspace]
# Try
# require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = [
    "burn",
    "burn-autodiff",
    "burn-fusion",
    "burn-candle",
    "burn-common",
    "burn-compute",
    "burn-core",
    "burn-dataset",
    "burn-derive",
    "burn-import",
    "burn-import/onnx-tests",
    "burn-ndarray",
    "burn-no-std-tests",
    "burn-tch",
    "burn-wgpu",
    "burn-candle",
    "burn-tensor-testgen",
    "burn-tensor",
    "burn-train",
    "xtask",
    "examples/*",
    "backend-comparison",
]

exclude = ["examples/notebook"]

[workspace.package]
edition = "2021"
version = "0.12.0"
readme = "README.md"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
async-trait = "0.1.74"
bytemuck = "1.14"
const-random = "0.1.17"
csv = "1.3.0"
dashmap = "5.5.3"
dirs = "5.0.1"
fake = "2.9.1"
flate2 = "1.0.28"
float-cmp = "0.9.0"
getrandom = { version = "0.2.11", default-features = false }
gix-tempfile = { version = "11.0.0", features = ["signals"] }
hashbrown = "0.14.2"
indicatif = "0.17.7"
js-sys = "0.3.65"
libm = "0.2.8"
log = { default-features = false, version = "0.4.20" }
pretty_assertions = "1.4"
proc-macro2 = "1.0.69"
protobuf-codegen = "3.3"
quote = "1.0.33"
r2d2 = "0.8.10"
r2d2_sqlite = { version = "0.23.0" }
rayon = "1.8.0"
rmp-serde = "1.1.2"
rstest = "0.18.2"
rusqlite = { version = "0.30.0" }
sanitize-filename = "0.5.0"
serde_rusqlite = "0.34.0"
serde-wasm-bindgen = "0.6.1"
spin = { version = "0.9.8", features = ["mutex", "spin_mutex"] }
strum = "0.25.0"
strum_macros = "0.25.3"
syn = { version = "2.0", features = ["full", "extra-traits"] }
tempfile = "3.8.1"
thiserror = "1.0.50"
tracing-appender = "0.2.3"
tracing-core = "0.1.32"
tracing-subscriber = "0.3.18"
wasm-bindgen = "0.2.88"
wasm-bindgen-futures = "0.4.38"
wasm-logger = "0.2.0"
wasm-timer = "0.2.5"
console_error_panic_hook = "0.1.7"
reqwest = "0.11.23"


# WGPU stuff
futures-intrusive = "0.5"
pollster = "0.3"
text_placeholder = { version = "0.5.0", features = ["struct_context"] }
wgpu = "0.18.0"

#
# The following packages disable the "std" feature for no_std compatibility
#
bincode = { version = "2.0.0-rc.3", features = [
    "alloc",
    "serde",
], default-features = false }
derive-new = { version = "0.5.9", default-features = false }

half = { version = "2.3.1", features = [
    "alloc",
    "num-traits",
    "serde",
], default-features = false }
ndarray = { version = "0.15.6", default-features = false }
num-traits = { version = "0.2.17", default-features = false, features = [
    "libm",
] } # libm is for no_std
rand = { version = "0.8.5", default-features = false, features = [
    "std_rng",
] } # std_rng is for no_std 
rand_distr = { version = "0.4.3", default-features = false }
serde = { version = "1.0.192", default-features = false, features = [
    "derive",
    "alloc",
] } # alloc is for no_std, derive is needed
serde_json = { version = "1.0.108", default-features = false }
uuid = { version = "1.5.0", default-features = false }

[profile.dev]
debug = 0 # Speed up compilation time and not necessary.
