[package]
name = "xtask"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.8", features = ["derive"] }
derive_more = { version = "0.99.17", features = ["display"], default-features = false }
env_logger = "0.10.0"
log = "0.4.17"
rand = { workspace = true, features = ["std"] }
serde_json = { version = "1" }

[dev-dependencies]
rstest = { workspace = true }
