[package]
authors = ["louisfd <louisfd94@gmail.com>"]
categories = ["science"]
description = "This crate is used to time the execution of various computations, from operation kernels to complex model scenarios."
edition.workspace = true
license.workspace = true
name = "backend-comparison"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/backend-comparison"
version.workspace = true

[features]
default = ["std"]
std = []
candle-cpu = ["burn/candle"]
candle-cuda = ["burn/candle", "burn/cuda"]
candle-metal = ["burn/candle", "burn/metal"]
candle-accelerate = ["burn/candle", "burn/accelerate"]
ndarray = ["burn/ndarray"]
ndarray-blas-accelerate = ["burn/ndarray", "burn/accelerate"]
ndarray-blas-netlib = ["burn/ndarray", "burn/blas-netlib"]
ndarray-blas-openblas = ["burn/ndarray", "burn/openblas"]
tch-cpu = ["burn/tch"]
tch-gpu = ["burn/tch"]
wgpu = ["burn/wgpu"]
wgpu-fusion = ["burn/default", "burn/wgpu", "burn/fusion"]

[dependencies]
burn = { path = "../burn" }
derive-new = { workspace = true }
rand = { workspace = true }
burn-common = { path = "../burn-common", version = "0.13.0" }
serde_json = { workspace = true }
dirs = "5.0.1"

[dev-dependencies]


[[bench]]
name = "unary"
harness = false

[[bench]]
name = "binary"
harness = false

[[bench]]
name = "matmul"
harness = false

[[bench]]
name = "data"
harness = false

[[bench]]
name = "custom_gelu"
harness = false
